### ISSUE TITLE
change event passes value and not the event

### ISSUE THREAD

**Issue by rmcsharry** [webcat12345/ngx-ui-switch#239]
It seems from my usage that this:

`<ui-switch (change)="onChange($event)"></ui-switch>`

does not pass the $event, but actually $event.target.value. This means if I put the switch in a place where I don't want other clicks to be fired (stopPropagation of the event) I have to do this:

template
```html
                  <ui-switch
                    [checked]="card.is_follow_up"
                    (click)="onIsFollowUpClicked($event)"
                    (change)="onIsFollowUpChanged($event)">
                  </ui-switch>
```
code
```js
  public onIsFollowUpClicked($event: Event): void {
    $event.stopPropagation();
  }

  public onIsFollowUpChanged(value: boolean): void {
    this.card.is_follow_up = value;
}
```

I would expect the change event to pass the event, not the value?

**Comment by cmckni3** [comment]
Well, what happens with `$event` is up to directive/component that has the `EventEmitter`. `$event` must be used in the template for whatever value is returned because that's how Angular gets data from the `EventEmitter`.

I can see the use case for this.

I propose having 2 methods added, `onChangeEvent` and `onValueChange`. Something to that effect. Maybe even a single method that returns a single structure that wraps the event and value.

**Comment by cmckni3** [comment]
Haven't forgotten about this. Almost finished with it.

**Comment by cmckni3** [comment]
Changed in 2.1.0
